yolink:
  base_url: "https://api.yosmart.com/"  # This is the Yolink API base URL.
  uaid: "your_uaid"
  secret_key: "your_secret_key"
  token: ""  # Placeholder for storing the generated access token
mqtt:
  url: "mqtt://api.yosmart.com"
  port: 8003
  topic: "yl-home/${Home ID}/+/report"
files:
  device_file: "devices.yaml"
  map_file: "mappings.yaml"
chekt:
  ip: "192.168.1.100"
  port: 30003
  api_token: ""
monitor:
  api_key: "your_monitor_api_key"  # Add your monitor API key here
timezone: "America/Denver"  # Set the default timezone here
users: {}
