yolink:
  uaid: "your_uaid"           # Replace with your actual UAID
  secret_key: "your_secret_key"  # Replace with your actual Secret Key, unencrypted initially
  token: ""
  token_expiry: 0

mqtt:
  url: "mqtt://api.yosmart.com"
  port: 8003
  topic: "yl-home/${Home ID}/+/report"
  username: ""
  password: ""

mqtt_monitor:
  url: "mqtt://monitor.industrialcamera.com"
  port: 1883
  username: ""
  password: ""

receiver_type: "CHEKT"

chekt:
  api_token: "your_chekt_api_token"  # Replace with actual token
  ip: "192.168.1.100"
  port: 30003

sia:
  ip: "192.168.1.101"
  port: 30004
  account_code: "your_sia_account_code"
  encryption_key: "your_sia_encryption_key"

monitor:
  api_key: "your_monitor_api_key"  # Replace with actual key

timezone: "America/Denver"

door_open_timeout: 30

users: {}