yolink:
  url: "http://192.168.1.100:8080"  # Yolink local bridge API URL
  uac: "your_uac_value_here"
  csseckey: "your_csseckey"
  token: "your_token"
mqtt:
  url: "mqtt://192.168.1.100"
  port: 1883
  topic: "/yolink/events"
chekt:
  ip: "192.168.1.101"
  port: 30003
files:
  device_file: "devices.yaml"
  map_file: "mappings.yaml"
