yolink:
  base_url: "https://api.yosmart.com/"  # YoLink API base URL
  uaid: "your_uaid"
  secret_key: "your_secret_key"
  token: ""  # Placeholder for storing the generated access token

mqtt_monitor:
  url: 'mqtt://monitor.industrialcamera.com'
  port: 1883
  username: '<mqtt_user>'
  password: '<password>'
  client_id: 'monitor_client_id'  # Optional

mqtt:
  url: "mqtt://api.yosmart.com"
  port: 8003
  topic: "yl-home/${Home ID}/+/report"

files:
  device_file: "devices.yaml"
  map_file: "mappings.yaml"

# Define the receiver type and settings for CHEKT and SIA
receiver_type: "CHEKT"  # Options: "CHEKT" or "SIA"

# CHEKT Configuration
chekt:
  ip: "192.168.1.100"
  port: 30003
  api_token: "your_chekt_api_token"  # CHEKT API token

# SIA Configuration
sia:
  ip: "192.168.1.101"  # IP address of the SIA receiver
  port: 30004          # Port for the SIA receiver
  account_code: "your_sia_account_code"  # SIA account code
  encryption_key: "your_sia_encryption_key"  # SIA encryption key (if needed)

monitor:
  api_key: "your_monitor_api_key"  # Monitor API key

mqtt_monitor:
username: 'mqtt_user'
password: 'SKunkworks1!"

timezone: "America/Denver"  # Default timezone

users: {}


chekt:
  api_token: Q0tCNTExMjU2LXBu.2z9isHkAV9Q8qkjg8Womy8txBok
  ip: 10.250.250.72
  port: '30003'
mqtt:
  port: 8003
  topic: yl-home/${Home ID}/+/report
  url: mqtt://api.yosmart.com
timezone: America/Denver
users:
  lazerusrm:
    password: $2b$12$S8pxgNMwI6CT8chALR15oe0XktLaY0v5TCRRc/9qYzYgr8PEHqC76
    totp_secret: UBISMR5YBOWYZCBHZ76PXQWW6HZMFW5Q
yolink:
  secret_key: sec_v1_h0K5kZpcupZt35GdBkIfXw==
  uaid: ua_DBCAA464829A474EA5F272B4428CD4CE
