yolink:
  url: "https://api.yosmart.com"
  uaid: "your_uaid"
  secret_key: "your_secret_key"
  url: "https://api.yosmart.com/openApi"  # This is the Yolink API base URL.
  token: "your_access_token_here"  # Placeholder for storing the generated access token
mqtt:
  url: "mqtt://broker.yosmart.com"
  port: 1883
  topic: "/yolink/events"
files:
  device_file: "devices.yaml"
  map_file: "mappings.yaml"
chekt:
  ip: "192.168.1.100"
  port: 30003
  api_token: ""