services:
  yolink_chekt:
    build: .
    ports:
      - "5000:5000"  # Map port 5000 on the container to port 5000 on the host
    volumes:
      - ./config.yaml:/app/config.yaml  # Map config.yaml from host to container
      - ./devices.yaml:/app/devices.yaml  # Map devices.yaml from host to container
      - ./mappings.yaml:/app/mappings.yaml  # Map mappings.yaml from host to container
      - ./templates/:/app/templates/  # Ensure templates directory (with config.html) is mapped to /app/templates