services:
  yolink_chekt:
    build: .
    ports:
      - "5000:5000"  # Map port 5000 on the container to port 5000 on the host
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - LOG_DIR=/app/logs
    restart: unless-stopped  # Ensure the container restarts automatically unless stopped manually