version: '3'

services:
  yolink_chekt:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - LOG_DIR=/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - yolink-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - yolink-network

  websocket-proxy:
    build:
      context: .
      dockerfile: websocket-proxy/Dockerfile
    container_name: yolink-websocket-proxy
    restart: unless-stopped
    environment:
      - PORT=3000
      - API_URL=http://yolink_chekt:5000/get_sensor_data
      - FETCH_INTERVAL=5000
    ports:
      - "3010:3000"
    depends_on:
      - yolink_chekt
    networks:
      - yolink-network

  rtsp-streamer:
    build:
      context: ./rtsp-streamer
      dockerfile: Dockerfile
    container_name: yolink-rtsp-streamer
    restart: unless-stopped
    environment:
      - DASHBOARD_URL=http://websocket-proxy:3000
      - RTSP_PORT=8554
      - STREAM_NAME=yolink-dashboard
      - FRAME_RATE=6
      - WIDTH=1920
      - HEIGHT=1080
      - CYCLE_INTERVAL=10000
      - ENABLE_ONVIF=true
      - ONVIF_PORT=8555
      - SERVER_IP=0.0.0.0
      - RTSP_API_PORT=3001
      - WS_PORT=9999
      - ENABLE_LOW_RES_PROFILE=true
      - ENABLE_MOBILE_PROFILE=false
      - LOW_RES_WIDTH=960
      - LOW_RES_HEIGHT=540
      - LOW_RES_FPS=6
      - LOW_RES_BITRATE=256
      - LOW_RES_SENSORS_PER_PAGE=6
      - SENSORS_PER_PAGE=20
    ports:
      - "8554:8554"
      - "3001:3001"
      - "9999:9999"
      - "3702:3702/udp"
    volumes:
      - /tmp/streams:/tmp/streams
    depends_on:
      - websocket-proxy
    networks:
      - yolink-network

networks:
  yolink-network:

volumes:
  redis-data:
