version: '3'
services:
  yolink_chekt:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./devices.yaml:/app/devices.yaml
      - ./mappings.yaml:/app/mappings.yaml

  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
