services:
  yolink_chekt:
    build: .
    ports:
      - "5000:5000"  # Map port 5000 on the container to port 5000 on the host
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./devices.yaml:/app/devices.yaml
      - ./mappings.yaml:/app/mappings.yaml